### ISSUE TITLE
No Call history with FW 6.30

### ISSUE THREAD

**Issue by jowi24** [jowi24/kfritz#1]
After updating the fritzbox-firmware from 6.23 to 6.30 the call history is missing. A empty screen is shown. But Fritz!Box phone books are listened as before.

Reported via mail by: Heinrich Kieneke

**Comment by gauda** [comment]
I have this error, too:
    [libfritz++/FritzClient.cpp:365] sending callList update request.
    [libfritz++/FritzClient.cpp:410] Exception in connection to fritz.box - Arbitrary error occured
    [libfritz++/FritzClient.cpp:410] waiting 60 seconds before retrying

Fritzbox 7390
FRITZ!OS 06.30
KFritz 0.0.12a

**Comment by jowi24** [comment]
I have no problems using KFritz 0.0.14 after upgrading a Fritzbox 7390 to the current firmware 06.30. Please try again with the newest KFritz version. Does this fix the issue for you?

**Comment by gauda** [comment]
Yes, this fixes the error. Thank you!

**Comment by jowi24** [comment]
Great, thank you for your feedback!
