### ISSUE TITLE
Cannot compile: No rule to make target

### ISSUE THREAD

**Issue by gauda** [jowi24/kfritz#2]
I just cloned the repository with the following result:

```
$ uname -a
Linux xxx 3.13.0-61-generic #100-Ubuntu SMP Wed Jul 29 11:21:34 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
Description:    Ubuntu 14.04.3 LTS

$ kdeinit4 --version
Qt: 4.8.6
KDE: 4.14.2

$ make --version
GNU Make 3.81

$ LANG=en make
make: *** No rule to make target `libfritz++/*.cpp', needed by `LibFritzI18N.cpp'.  Stop.
```

Do you have any hint for me how to compile this?

**Comment by jowi24** [comment]
The repository includes git submodules, i.e. you have to add " --recursive" to the git clone command to get the full source.

**Comment by gauda** [comment]
Thanks. With your help I was able to compile successfully!
