### ISSUE TITLE
Doesn't ask for user when FritzBox is set to user/password auth

### ISSUE THREAD

**Issue by LeoVerto** [jowi24/kfritz#3]
I use the user/password mode in my FritzBox for better client management but unfortunately it looks like KFritz doesn't support this yet and only asks for a password to log into the FB.

**Comment by jowi24** [comment]
Username authentication is available since kfritz-0.0.13 (12-2013), see 5b4b524e298a9fac8bb9d9318483d6871fd6a3b4. What version do you use?

**Comment by LeoVerto** [comment]
I'm sorry for this huge oversight of mine, I really should've checked if I was using the latest version before reporting this.

Of course the Ubuntu package is outdated (0.12a).

Thank you for making kfritz (and of course those awesome VDR builds). :D

**Comment by jowi24** [comment]
Glad to hear it works for you :)
